# Generated by Django 3.1.5 on 2021-01-18 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210118_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_urls',
            name='expiry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
