# Generated by Django 3.1.5 on 2021-01-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user_urls_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_date', models.DateTimeField()),
                ('original_url', models.URLField()),
                ('short_char', models.CharField(blank=True, max_length=8)),
                ('visits', models.IntegerField(default=0)),
                ('expiry', models.DateTimeField(blank=True)),
            ],
        ),
    ]
