# Generated by Django 3.1.5 on 2021-01-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_public_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_urls',
            name='title',
            field=models.CharField(default='No Title', max_length=10),
        ),
        migrations.AlterField(
            model_name='public_urls',
            name='short_char',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='user_urls',
            name='short_char',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
